ENV ?= dev
ENV_FILE ?= envs/$(ENV).env
COMPOSE := docker compose --env-file $(ENV_FILE) -f infra/docker-compose.yml

CYAN  := \033[36m
RESET := \033[0m
ARROW := $$'\xe2\x96\xb6'

.PHONY: banner help up down clean logs rebuild restart shell ps \
        test test-docker lint lint-check fmt \
        migrate upgrade downgrade history \
        current heads revision stamp db-shell db-tables db-version check-mgt
banner:
	@printf "\033[36m==> ENV=%s  file=%s\033[0m\n" "$(ENV)" "$(ENV_FILE)"
	
help: banner ## show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}'

up: banner ## start full stack
	$(COMPOSE) up -d

down: banner ## stop stack
	$(COMPOSE) down

clean: banner ## stop stack and remove volumes
	$(COMPOSE) down -v

logs: banner ## tail backend logs
	-$(COMPOSE) logs -f backend

rebuild: banner ## rebuild backend image
	$(COMPOSE) build backend

restart: banner ## restart backend container
	$(COMPOSE) restart backend

shell: banner ## open shell inside backend container
	$(COMPOSE) exec backend bash

db-shell: banner ## open psql inside the postgres container
	$(COMPOSE) exec postgres sh -c 'psql -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"'

ps: banner ## list running containers
	$(COMPOSE) ps

test: banner ## run pytest on host
	cd backend && uv run pytest -v "$(m)"

test-docker: banner ## run pytest inside backend container
	$(COMPOSE) exec backend uv run pytest -v

lint: banner ## ruff --fix + format + mypy
	cd backend && uv run ruff check . --fix && uv run ruff format . && uv run mypy app

lint-check: banner ## ruff + mypy (CI, no writes)
	cd backend && uv run ruff check . && uv run mypy app

fmt: banner ## ruff format only
	cd backend && uv run ruff format .

migrate: banner ## create autogenerated revision (m='msg')
	@test -n "$(m)" || (echo "usage: make migrate m='add users table'"; exit 1)
	$(COMPOSE) exec backend alembic revision --autogenerate -m "$(m)"

upgrade: banner ## apply all migrations
	$(COMPOSE) exec backend alembic upgrade head

downgrade: banner ## roll back one migration
	$(COMPOSE) exec backend alembic downgrade -1

history: banner ## show migration history
	$(COMPOSE) exec backend alembic history

current: banner ## show the revision Alembic thinks is applied
	$(COMPOSE) exec backend alembic current

heads: banner ## show all migration heads (should be one)
	$(COMPOSE) exec backend alembic heads

revision: banner ## create empty revision (m='msg')
	@test -n "$(m)" || (echo "usage: make revision m='message'"; exit 1)
	$(COMPOSE) exec backend alembic revision -m "$(m)"


stamp: banner ## stamp DB to a revision without running migrations (rev=base or hash)
	@test -n "$(rev)" || (echo "usage: make stamp rev=base"; exit 1)
	$(COMPOSE) exec backend alembic stamp "$(rev)"

db-tables: banner ## list tables in the DB
	$(COMPOSE) exec postgres sh -c 'psql -U "$$POSTGRES_USER" -d "$$POSTGRES_DB" -c "\dt"'

db-version: banner ## read alembic_version directly from the DB
	$(COMPOSE) exec postgres sh -c 'psql -U "$$POSTGRES_USER" -d "$$POSTGRES_DB" -c "SELECT * FROM alembic_version;"'

check-mgt: banner ## verify DB matches models
	$(COMPOSE) exec backend alembic check

worker-logs:  banner ## check worker
	$(COMPOSE) logs -f worker