"""add content parsed_key

Revision ID: 1cb4fe9dc3e5
Revises: bf94e3fc14b3
Create Date: 2026-09-20 23:22:31.229300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy



# revision identifiers, used by Alembic.
revision: str = '1cb4fe9dc3e5'
down_revision: Union[str, Sequence[str], None] = 'bf94e3fc14b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('parsed_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'parsed_key')
    # ### end Alembic commands ###
