"""add content hash and storage key

Revision ID: bf94e3fc14b3
Revises: 1931fca3709c
Create Date: 2026-09-20 21:44:09.910391

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf94e3fc14b3"
down_revision: str | Sequence[str] | None = "1931fca3709c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("storage_key", sa.String(length=256), nullable=True))
    op.add_column("documents", sa.Column("content_hash", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "content_hash")
    op.drop_column("documents", "storage_key")
    # ### end Alembic commands ###
